name: flutter_summernote
description: Text Editor in Flutter for Android and iOS to help free write
  WYSIWYG HTML code based on Summernote 0.8.18 javascript wrapper.
version: 1.1.1
homepage: https://summernote.org
repository: https://github.com/chandrabezzo/flutter_summernote
documentation: https://summernote.org
issue_tracker: https://github.com/chandrabezzo/flutter_summernote/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  path: ^1.9.0
  mime: ^2.0.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter